# -*- coding: utf-8 -*-
"""Praticse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18D0lsdC9FQ2yGs-e8JEVW0snhUPedwtD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/Obesity_Dataset.csv')
dataset

dataset.info()

dataset.isnull().sum()

dataset.shape

sns.distplot(dataset.Age)

dataset['Height'].median()

sns.distplot(dataset.Consumption_of_Fast_Food )

sns.countplot(x = 'Age', data = dataset)

